### ISSUE TITLE
404 error in workbench, but not in my local cli

### ISSUE THREAD

**Issue by aborruso** [tobilg/sql-workbench#22]
Hi,
thank you for this great tool.

If I run this query in sql-workbench

```sql
SELECT
  "CUP"
FROM
  read_csv_auto(
    'https://www.italiadomani.gov.it/content/dam/sogei-ng/opendata/PNRR_Pagamenti_di_Progetto.csv',
    decimal_separator = ','
  )
LIMIT 5
```

I have "Invalid Error: NetworkError: Fai led to execute send on XMLHttpRequest: Failed to load https://waw.ita1iadomani.gov.it/content/dam/sogei-ng/opendata/PNRR_Pagamenti_di_Progetto.csv."

But if I run it via cli, I have the right query result.

Is it normal? It is an HTTP response problem?

Thank you

**Comment by tobilg** [comment]
Thanks for reporting! Unfortunately, that server doesn't send a CORS header:

![image](https://github.com/user-attachments/assets/668716a6-d561-44ce-86fd-30479d97be21)

As SQL Workbench is using DuckDB WASM running in the browser, browser security mechanisms apply that don't exist in the CLI (non-browser). You could try to access this file with a CORS proxy, otherwise I unfortunately can't do anything to change this behavior...

**Comment by aborruso** [comment]
Thank you very much

**Comment by tobilg** [comment]
@aborruso I just deployed a CORS proxy that works specifically with https://sql-workbench.com

Try the following:

```sql
SELECT
  *
FROM
  read_csv_auto(
    'https://cors.sqlqry.run/?url=https://www.italiadomani.gov.it/content/dam/sogei-ng/opendata/PNRR_Pagamenti_di_Progetto.csv'
  )
LIMIT 5;
```

**Comment by aborruso** [comment]
Wow, it works!

Have a nice 2025

**Comment by tobilg** [comment]
Thanks, you too! I added it to the docs as well: https://sql-workbench.com/docs/using-the-cors-proxy

**Comment by aborruso** [comment]
Hi, not strictly related: I published a post today, in which I show how to use duckdb as a data catalog.
So the tables are just views of remote parquet files. 

And in this post, I also showed how convenient it is to use your fantastic tool. 

It's in Italian.

https://aborruso.github.io/posts/tutto-il-pnrr-in-500k/
